service: andersons-space
provider: 
  name: aws
  region: eu-north-1
frameworkVersion: '3'
 
resources:
  Resources:
    AndersonsSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Allow HTTP traffic to the ECS instances
        GroupName: andersons_security-group
        VpcId: vpc-0a1a9acefbe3de0b7
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0

    AndersonsCluster:
      Type: AWS::ECS::Cluster
      Properties:
        ClusterName: andersons_cluster

    AndersonsClusterEC2Instance:
      Type: AWS::EC2::Instance
      Properties:
        InstanceType: t3.micro
        ImageId: ami-0cf72be2f86b04e9b
        KeyName: andersons.space
        SecurityGroupIds:
          - !Ref AndersonsSecurityGroup
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: 30
              VolumeType: gp2
              DeleteOnTermination: false
        Tags:
          - Key: Name
            Value: andersons.space
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            echo ECS_CLUSTER=${AndersonsCluster} >> /etc/ecs/ecs.config
            yum update -y
            yum install -y aws-cli
          # aws s3 cp s3://<your-ecs-config-bucket>/ecs.config /etc/ecs/ecs.config

  Outputs:
    ECSClusterName:
      Value: !Ref AndersonsCluster